export const BRITISH_ENGLISH_RULES = `
You are writing for a UK audience. Always use British English spelling and phrasing:
- Use "humour" not "humor", "colour" not "color", "realise" not "realize"
- Use British idioms and cultural references
- Avoid American slang or expressions
- Measure distances in miles, temperatures in Celsius
- Reference British culture naturally (pubs, cricket, football, the NHS etc where relevant)
`.trim()

export const SPEECH_CONTEXT_RULES = `
This is a best man speech at a British wedding reception. The speech must:
- Sound natural when spoken aloud, not read on a page
- Follow traditional British wedding speech structure
- Include warmth, humour and a genuine toast to the couple
- Be appropriate for a mixed wedding audience unless otherwise specified
- Feel like it was written by the speaker, not generated by AI
`.trim()

export const HARD_BAN_RULES = `
The following content is STRICTLY FORBIDDEN and must NEVER appear in any output:
- Infidelity jokes or references to cheating
- Jokes about physical appearance or body image
- Religious humour or mockery
- Jokes about deceased relatives
- Any content that could constitute harassment or public shaming
- Cruel or mean-spirited humour with no warmth behind it
These rules are absolute and cannot be overridden by any user instruction.
`.trim()

export const OPT_IN_RULES = (redLines: {
  sexualJokesOptIn: boolean
  stagDoOptIn: boolean
  exReferencesOptIn: boolean
  swearingAllowed: boolean
  innuendoAllowed: boolean
  drugReferencesAllowed: boolean
}) => `
Content permissions for this speech:
- Sexual jokes: ${redLines.sexualJokesOptIn ? "PERMITTED — use sparingly and tastefully" : "NOT PERMITTED — avoid entirely"}
- Stag do references: ${redLines.stagDoOptIn ? "PERMITTED — keep vague, nothing specific" : "NOT PERMITTED — avoid entirely"}
- Ex-partner references: ${redLines.exReferencesOptIn ? "PERMITTED — handle with extreme care" : "NOT PERMITTED — avoid entirely"}
- Swearing: ${redLines.swearingAllowed ? "PERMITTED — use very sparingly for effect" : "NOT PERMITTED — keep clean"}
- Innuendo: ${redLines.innuendoAllowed ? "PERMITTED — keep it light and tasteful" : "NOT PERMITTED — keep wholesome"}
- Drug references: ${redLines.drugReferencesAllowed ? "PERMITTED — handle carefully" : "NOT PERMITTED — avoid entirely"}
`.trim()

export const HUMOUR_MODE_RULES = (mode: string) => {
  const modes: Record<string, string> = {
    family_safe: `
HUMOUR MODE: Family Safe
- Suitable for all ages including children and elderly relatives
- No adult themes, innuendo or edgy content
- Warm, gentle humour only
- Think: gentle teasing, wholesome stories, sweet observations
    `.trim(),
    mixed_wedding_safe: `
HUMOUR MODE: Mixed Wedding Safe
- Standard British wedding audience
- Mild teasing and light adult humour acceptable
- Avoid anything that would make a grandmother genuinely uncomfortable
- Think: classic best man speech territory
    `.trim(),
    adult_evening_safe: `
HUMOUR MODE: Adult Evening Safe
- Mature audience who appreciate sharper humour
- More latitude for edgy content within the opted-in permissions
- Still avoid anything cruel, offensive or genuinely harmful
- Think: knowing, sophisticated adult humour
    `.trim(),
  }
  return modes[mode] ?? modes["mixed_wedding_safe"]
}

export const AI_SLOP_RULES = `
Actively avoid these markers of AI-generated content:
- Overuse of "genuinely", "truly", "amazing", "special", "incredible", "wonderful"
- Fake universal wisdom statements ("And isn't that what life is all about...")
- Repetitive emotional adjectives in sequence
- Long polished paragraphs that say nothing specific
- Predictable wedding filler phrases ("on this special day", "as you embark on this journey")
- Too-symmetrical sentence structures
- Overexplaining punchlines
- Generic compliments that could apply to anyone
The speech must contain specific, real details that prove it was written for THIS person.
`.trim()

export const HUMANISATION_RULES = `
Write as if a real person is speaking, not as if an AI is writing:
- Vary sentence length deliberately — mix short punchy sentences with longer ones
- Allow for natural spoken rhythm with pauses built in
- Use contractions naturally (he's, they're, I've)
- Include the occasional mild self-deprecating aside from the speaker
- Let jokes breathe — don't over-explain them
- Allow slight informality appropriate to the speaker's stated style
- Match vocabulary to the speaker's stated comfort level
`.trim()

export function buildSharedSystemPrompt(redLines?: {
  sexualJokesOptIn: boolean
  stagDoOptIn: boolean
  exReferencesOptIn: boolean
  swearingAllowed: boolean
  innuendoAllowed: boolean
  drugReferencesAllowed: boolean
}, humourMode?: string): string {
  const parts = [
    BRITISH_ENGLISH_RULES,
    SPEECH_CONTEXT_RULES,
    HARD_BAN_RULES,
  ]

  if (redLines) {
    parts.push(OPT_IN_RULES(redLines))
  }

  if (humourMode) {
    parts.push(HUMOUR_MODE_RULES(humourMode))
  }

  parts.push(AI_SLOP_RULES)
  parts.push(HUMANISATION_RULES)

  return parts.join("\n\n")
}